# Generated by Django 3.2.13 on 2022-05-04 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('email', models.EmailField(max_length=100, verbose_name='Correo electrónico')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.address')),
            ],
        ),
    ]
