# Generated by Django 3.2.13 on 2022-05-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ManyToManyField(related_name='direcciones', to='client.Address'),
        ),
    ]
